 const serviceData = [
  {
    id: "NuSpine ",
    name: "NuSpine",
    badge: "chiropractor",
    image: "https://lirp.cdn-website.com/264047a3/dms3rep/multi/opt/NuSpine+-+1+Full-1920w.png",
    description:
      "Trusted by Thousands of Patients for Five Star Proven Relief",
    contact: "+1 7024770000",
    email: "",
    address: "4965 Blue Diamond Rd. Ste. 115 Las Vegas, NV 89139",
    link: "https://www.nuspine.com/",
  },
    {
    id: "Advance Health Care of Henderson",
    name: "Advance Health Care of Henderson",
    badge: "Health Care",
    image: "https://www.ahcfacilities.com/wp-content/uploads/2024/04/AHC-Henderson-Logo-Color-01.png",
    description:"Specializes in short-term nursing and rehabilitation. Offers private suites, 24-hour nursing care, inpatient rehabilitation...",
    contact: "+1 7024770000",
    email: "",
    address: "1285 E Cactus Ave, Las Vegas, NV 89183",
    link: "https://www.ahcfacilities.com/henderson",
  },
    {
    id: "CareFirst Urgent Care - Vegas ",
    name: "CareFirst Urgent Care - Vegas ",
    badge: "Urgent Care",
    image: "https://s3.amazonaws.com/urgentq_production/uploads/hospital/logo/7329/CareFirst_Logo.jpg",
    description:"",
    contact: "+1 7024770000",
    email: "",
    address: "4360 Blue Diamond Rd SUITE 103, Las Vegas, NV 89139",
    link: "https://www.carefirsturgentcares.com/locations/blue-diamond-nv/",
  },
    {
    id: "CareNow Urgent Care  ",
    name: "CareNow Urgent Care ",
    badge: "Online Care ",
    image: "https://www.hcadam.com/api/public/content/783a61801d5043d7b645a0282b088c74?v=ad919953",
    description:"At our walk-in care clinic in Southwest Las Vegas, dedicated physicians provide expert treatment for a wide range of minor medical conditions.",
    contact: "+1  (702) 464-3213",
    email: "",
    address: "7424 S Rainbow Blvd Suite A, Las Vegas, NV 89139",
    link: "https://www.carenow.com/locations/las-vegas/rainbow-mardon?utm_campaign=corp_listings_mgmt&utm_source=google&utm_medium=business_listing",
  },
   
    {
    id: "Sunset Ridge Post ",
    name: "Sunset Ridge Post ",
    badge: "chiropractor",
    image: "https://sunsetridgepost.com/wp-content/uploads/sites/186/2026/01/sunsetridge2_color.png",
    description:"r team of professionals are dedicated to caring for you after a surgery, illness, or injury. ",
    contact: "+1 (702)470-1102",
    email: "",
    address: "5650 S Rainbow Blvd, Las Vegas, NV 89118",
    link: "https://sunsetridgepost.com/",
  },
  
  {
    id: "Intermountain Health Wynn ",
    name: "Intermountain Health Wynn ",
    badge: "Health Care",
    image: "https://intermountainhealthcare.org/_next/image?url=%2Fsc10media%2Fimages%2Fintermountain-health%2Fcomponents%2Fcallouts-and-highlights%2Ffeatures%2Ffemale-patient-medical-consultation.ashx%3Fh%3D800%26iar%3D0%26w%3D1200%26hash%3D8100F6995E1C11911CE5ADD265C4248D&w=1200&q=75",
    description: " Offering services from helping you get well to guiding you to live your healthiest life possible. They are here to support you every step of the way.",
    contact: "+1 (702)871-5005",
    email: "",
    address: "4880 S Wynn Rd., Las Vegas, NV 89103",
    link: "https://intermountainhealthcare.org/",
  },
  {
    id: "Oakey Health Care Center",
    name: "Oakey Health Care Center",
    badge: "Health Care",
    image: "https://www.optum.com/content/dam/optum4/images/logos/optum-logo-ora-rgb1.svg",
    description:"In addition to health care, offers health finances, online pharmacy, health care description with tips for a healthier life.",
    contact: "+1 (702) 877-5088 ",
    email: "",
    address: " 4750 W Oakey Blvd, Las Vegas, NV 89102",
    link: "https://www.optum.com/",
  },
  {
    id: "Southern Nevada  Health Center ",
    name: " Southern Nevada  Health Center ",
    badge: "Community Health Center",
    image: "https://snchc.org/wp-content/uploads/2021/04/snchc_logo_2x.png",
    description:"Federally Qualified Health Center at the Southern Nevada Health District. ",
    contact: "+1 (702) 759-1700 ",
    email: "",
    address: "123 Main St, Springfield, IL",
    link: "https://snchc.org/",
  },
  {
    id: "e7 Health ",
    name: " e7 Health",
    badge: "Health Center",
    image: "https://www.e7health.com/files/pages/las-vegas-47.jpg",
    description:"e7 Health specialize in travel medicine, student health, employee health, drug testing, STD testing, physical exams, immigration exams and laboratory services. ",
    contact: "+1 702-800-2723",
    email: "",
    address: "123 Main St, Springfield, IL",
    link: "https://www.e7health.com/lasvegas/",
  },
  
]
export default  serviceData
//gets mapped on CardDataRender.jsx